services:
  backend:
    build:
      context: ./backend
    container_name: food-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # Se “hornea” en el build de Vite
        - VITE_API_BASE_URL=http://backend:8000
    container_name: food-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped